name: Integration Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: [ "main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  FDS:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/simvue-io/fds_example
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          poetry install -E fds -E test
      - name: Run test
        run: poetry run pytest tests/integration/test_fds.py
  MOOSE:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          poetry install -E test
      - name: Run test
        run: poetry run pytest tests/integration/test_moose.py
  OpenFOAM:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/simvue-io/openfoam_example
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          poetry install -E test
      - name: Run test
        run: poetry run pytest tests/integration/test_openfoam.py
  TensorFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          poetry install -E tensorflow -E test
      - name: Run test
        run: poetry run pytest tests/integration/test_tensorflow.py
